# Generated by Django 2.1.7 on 2019-03-02 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'исход', 'verbose_name_plural': 'исходы'},
        ),
    ]
