# Generated by Django 2.1.7 on 2019-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='_step_choices_+', to='bot.Step',
                                         verbose_name='исходы'),
        ),
    ]
