# Generated by Django 2.1.7 on 2019-03-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_auto_20190302_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='second_message',
        ),
        migrations.AddField(
            model_name='step',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Step',
                                    verbose_name='следующий шаг'),
        ),
    ]
