# Generated by Django 2.1.7 on 2019-03-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0004_auto_20190302_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='next_step',
            field=models.ForeignKey(blank=True,
                                    help_text='Если указано, то сразу осуществляется переход к следующему шагу.',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Step',
                                    verbose_name='следующий шаг'),
        ),
    ]
