# Generated by Django 2.1.7 on 2019-03-02 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0005_auto_20190302_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='time_of_last_step',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время последнего действия'),
        ),
    ]
